### ISSUE TITLE
Constants.getWebViewUserAgentAsync() ?

### ISSUE THREAD

**Issue by LouisJS** [simpleanalytics/expo-test-app#2]
What do you obtain from `Constants.getWebViewUserAgentAsync()` that you cannot fetch from `Constants.platform` ?

> Constants.getWebViewUserAgentAsync()
Gets the user agent string which would be included in requests sent by a web view running on this device. This is probably **not** the same user agent you might be providing in your JS fetch requests.

**Comment by adriaanvanrossum** [comment]
We works with browser user agents always, so it's just easier for us at the moment. Not sure if it has any downsides, do you know of any?

**Comment by LouisJS** [comment]
No it should be fine :)

The `WebView` term in the description confused me

**Comment by adriaanvanrossum** [comment]
Ah cool, I will close it then.
